import 'package:flutter/material.dart';


void main() {
  runApp(const HomeScreen());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          HomeScreen(),
        ]),
      ),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 375,
                  height: 38.55,
                  decoration: BoxDecoration(color: Color(0xFF022E64)),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 20.15,
                        top: 9.64,
                        child: Text(
                          '9:41',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 14.02,
                            fontFamily: 'Urbanist',
                            fontWeight: FontWeight.w600,
                            height: 1.40,
                            letterSpacing: 0.18,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 292.64,
                        top: 15.77,
                        child: Container(
                          width: 15.77,
                          height: 8.76,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/16x9"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 312.79,
                        top: 14.89,
                        child: Container(
                          width: 13.38,
                          height: 9.61,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/13x10"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 331.19,
                        top: 14.02,
                        child: Container(
                          width: 23.64,
                          height: 11.39,
                          child: Stack(children: [
                          ]),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 516.50,
                child: Container(
                  height: 70.02,
                  padding: const EdgeInsets.symmetric(horizontal: 17.52, vertical: 12),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    border: Border(
                      left: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      top: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      right: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      bottom: BorderSide(
                        width: 0.75,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                    ),
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: double.infinity,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Expanded(
                              child: Container(
                                height: 46.02,
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(7.01),
                                      decoration: ShapeDecoration(
                                        color: Color(0xFFFDF8EC),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(87.62),
                                        ),
                                      ),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          Container(
                                            padding: const EdgeInsets.all(8),
                                            decoration: ShapeDecoration(
                                              gradient: LinearGradient(
                                                begin: Alignment(0.89, -0.45),
                                                end: Alignment(-0.89, 0.45),
                                                colors: [Color(0xFFE0AD0F), Color(0xFFA07701)],
                                              ),
                                              shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(100),
                                              ),
                                            ),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              crossAxisAlignment: CrossAxisAlignment.center,
                                              children: [
                                                Container(
                                                  width: 16,
                                                  height: 16,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 16,
                                                          height: 16,
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 5.33,
                                                                top: 5,
                                                                child: Container(
                                                                  width: 4.67,
                                                                  height: 6,
                                                                  child: Stack(children: [
                                                                  ]),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    const SizedBox(width: 14.02),
                                    Expanded(
                                      child: Container(
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Container(
                                              width: 280.37,
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                                crossAxisAlignment: CrossAxisAlignment.start,
                                                children: [
                                                  Container(
                                                    height: 22.51,
                                                    child: Row(
                                                      mainAxisSize: MainAxisSize.min,
                                                      mainAxisAlignment: MainAxisAlignment.start,
                                                      crossAxisAlignment: CrossAxisAlignment.center,
                                                      children: [
                                                        Text(
                                                          'GHC 10,000.00',
                                                          style: TextStyle(
                                                            color: Color(0xFF212121),
                                                            fontSize: 16,
                                                            fontFamily: 'Open Sans',
                                                            fontWeight: FontWeight.w700,
                                                            height: 1.20,
                                                          ),
                                                        ),
                                                        const SizedBox(width: 7.01),
                                                        Container(
                                                          padding: const EdgeInsets.symmetric(horizontal: 8.76, vertical: 5.26),
                                                          decoration: ShapeDecoration(
                                                            color: Color(0x14E0AD0F),
                                                            shape: RoundedRectangleBorder(
                                                              borderRadius: BorderRadius.circular(5.26),
                                                            ),
                                                          ),
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Text(
                                                                'Credit',
                                                                style: TextStyle(
                                                                  color: Color(0xFFE0AD0F),
                                                                  fontSize: 9,
                                                                  fontFamily: 'Open Sans',
                                                                  fontWeight: FontWeight.w600,
                                                                  letterSpacing: 0.18,
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                  const SizedBox(width: 8),
                                                  Text(
                                                    '01-02-2021',
                                                    style: TextStyle(
                                                      color: Color(0xFF616161),
                                                      fontSize: 10,
                                                      fontFamily: 'Open Sans',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1.40,
                                                      letterSpacing: 0.18,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            const SizedBox(height: 5.26),
                                            SizedBox(
                                              width: double.infinity,
                                              child: Text.rich(
                                                TextSpan(
                                                  children: [
                                                    TextSpan(
                                                      text: '#',
                                                      style: TextStyle(
                                                        color: Color(0xFFE0AD0F),
                                                        fontSize: 12,
                                                        fontFamily: 'Open Sans',
                                                        fontWeight: FontWeight.w700,
                                                        height: 1.40,
                                                        letterSpacing: 0.18,
                                                      ),
                                                    ),
                                                    TextSpan(
                                                      text: 'Deposit',
                                                      style: TextStyle(
                                                        color: Color(0xFF616161),
                                                        fontSize: 12,
                                                        fontFamily: 'Open Sans',
                                                        fontWeight: FontWeight.w400,
                                                        height: 1.40,
                                                        letterSpacing: 0.18,
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 445.04,
                child: Container(
                  height: 70.02,
                  padding: const EdgeInsets.symmetric(horizontal: 17.52, vertical: 12),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    border: Border(
                      left: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      top: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      right: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      bottom: BorderSide(
                        width: 0.75,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                    ),
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: double.infinity,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Expanded(
                              child: Container(
                                height: 46.02,
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(7.01),
                                      decoration: ShapeDecoration(
                                        color: Color(0x1478C8E1),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(87.62),
                                        ),
                                      ),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          Container(
                                            padding: const EdgeInsets.all(8),
                                            decoration: ShapeDecoration(
                                              gradient: LinearGradient(
                                                begin: Alignment(-0.96, 0.28),
                                                end: Alignment(0.96, -0.28),
                                                colors: [Color(0xFF022E64), Color(0xFF0E5CBD)],
                                              ),
                                              shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(876.17),
                                              ),
                                            ),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              crossAxisAlignment: CrossAxisAlignment.center,
                                              children: [
                                                Container(
                                                  width: 16,
                                                  height: 16,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 16,
                                                          height: 16,
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 5.33,
                                                                top: 5,
                                                                child: Container(
                                                                  width: 4.67,
                                                                  height: 6,
                                                                  child: Stack(children: [
                                                                  ]),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    const SizedBox(width: 14.02),
                                    Expanded(
                                      child: Container(
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Container(
                                              width: 280.37,
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                                crossAxisAlignment: CrossAxisAlignment.start,
                                                children: [
                                                  Container(
                                                    height: 22.51,
                                                    child: Row(
                                                      mainAxisSize: MainAxisSize.min,
                                                      mainAxisAlignment: MainAxisAlignment.start,
                                                      crossAxisAlignment: CrossAxisAlignment.center,
                                                      children: [
                                                        Text(
                                                          'GHC 1,000.00',
                                                          style: TextStyle(
                                                            color: Color(0xFF212121),
                                                            fontSize: 16,
                                                            fontFamily: 'Open Sans',
                                                            fontWeight: FontWeight.w700,
                                                            height: 1.20,
                                                          ),
                                                        ),
                                                        const SizedBox(width: 7.01),
                                                        Container(
                                                          padding: const EdgeInsets.symmetric(horizontal: 8.76, vertical: 5.26),
                                                          decoration: ShapeDecoration(
                                                            color: Color(0x1478C8E1),
                                                            shape: RoundedRectangleBorder(
                                                              borderRadius: BorderRadius.circular(5.26),
                                                            ),
                                                          ),
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Text(
                                                                'Debit',
                                                                style: TextStyle(
                                                                  color: Color(0xFF022E64),
                                                                  fontSize: 9,
                                                                  fontFamily: 'Open Sans',
                                                                  fontWeight: FontWeight.w600,
                                                                  letterSpacing: 0.18,
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                  const SizedBox(width: 8),
                                                  Text(
                                                    '01-02-2021',
                                                    style: TextStyle(
                                                      color: Color(0xFF616161),
                                                      fontSize: 10,
                                                      fontFamily: 'Open Sans',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1.40,
                                                      letterSpacing: 0.18,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            const SizedBox(height: 5.26),
                                            SizedBox(
                                              width: double.infinity,
                                              child: Text.rich(
                                                TextSpan(
                                                  children: [
                                                    TextSpan(
                                                      text: '#',
                                                      style: TextStyle(
                                                        color: Color(0xFF022E64),
                                                        fontSize: 12,
                                                        fontFamily: 'Open Sans',
                                                        fontWeight: FontWeight.w700,
                                                        height: 1.40,
                                                        letterSpacing: 0.18,
                                                      ),
                                                    ),
                                                    TextSpan(
                                                      text: 'Withdrawal',
                                                      style: TextStyle(
                                                        color: Color(0xFF616161),
                                                        fontSize: 12,
                                                        fontFamily: 'Open Sans',
                                                        fontWeight: FontWeight.w400,
                                                        height: 1.40,
                                                        letterSpacing: 0.18,
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 374.47,
                child: Container(
                  height: 70.02,
                  padding: const EdgeInsets.symmetric(horizontal: 17.52, vertical: 12),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    border: Border(
                      left: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      top: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      right: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      bottom: BorderSide(
                        width: 0.75,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                    ),
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: double.infinity,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Expanded(
                              child: Container(
                                height: 46.02,
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(7.01),
                                      decoration: ShapeDecoration(
                                        color: Color(0xFFFDF8EC),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(87.62),
                                        ),
                                      ),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          Container(
                                            padding: const EdgeInsets.all(8),
                                            decoration: ShapeDecoration(
                                              gradient: LinearGradient(
                                                begin: Alignment(0.89, -0.45),
                                                end: Alignment(-0.89, 0.45),
                                                colors: [Color(0xFFE0AD0F), Color(0xFFA07701)],
                                              ),
                                              shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(100),
                                              ),
                                            ),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              crossAxisAlignment: CrossAxisAlignment.center,
                                              children: [
                                                Container(
                                                  width: 16,
                                                  height: 16,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 16,
                                                          height: 16,
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 5.33,
                                                                top: 5,
                                                                child: Container(
                                                                  width: 4.67,
                                                                  height: 6,
                                                                  child: Stack(children: [
                                                                  ]),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    const SizedBox(width: 14.02),
                                    Expanded(
                                      child: Container(
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Container(
                                              width: 280.37,
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                                crossAxisAlignment: CrossAxisAlignment.start,
                                                children: [
                                                  Container(
                                                    height: 22.51,
                                                    child: Row(
                                                      mainAxisSize: MainAxisSize.min,
                                                      mainAxisAlignment: MainAxisAlignment.start,
                                                      crossAxisAlignment: CrossAxisAlignment.center,
                                                      children: [
                                                        Text(
                                                          'GHC 1,500.00',
                                                          style: TextStyle(
                                                            color: Color(0xFF212121),
                                                            fontSize: 16,
                                                            fontFamily: 'Open Sans',
                                                            fontWeight: FontWeight.w700,
                                                            height: 1.20,
                                                          ),
                                                        ),
                                                        const SizedBox(width: 7.01),
                                                        Container(
                                                          padding: const EdgeInsets.symmetric(horizontal: 8.76, vertical: 5.26),
                                                          decoration: ShapeDecoration(
                                                            color: Color(0x14E0AD0F),
                                                            shape: RoundedRectangleBorder(
                                                              borderRadius: BorderRadius.circular(5.26),
                                                            ),
                                                          ),
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Text(
                                                                'Credit',
                                                                style: TextStyle(
                                                                  color: Color(0xFFE0AD0F),
                                                                  fontSize: 9,
                                                                  fontFamily: 'Open Sans',
                                                                  fontWeight: FontWeight.w600,
                                                                  letterSpacing: 0.18,
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                  const SizedBox(width: 8),
                                                  Text(
                                                    '01-02-2021',
                                                    style: TextStyle(
                                                      color: Color(0xFF616161),
                                                      fontSize: 10,
                                                      fontFamily: 'Open Sans',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1.40,
                                                      letterSpacing: 0.18,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            const SizedBox(height: 5.26),
                                            SizedBox(
                                              width: double.infinity,
                                              child: Text.rich(
                                                TextSpan(
                                                  children: [
                                                    TextSpan(
                                                      text: '#',
                                                      style: TextStyle(
                                                        color: Color(0xFFE0AD0F),
                                                        fontSize: 12,
                                                        fontFamily: 'Open Sans',
                                                        fontWeight: FontWeight.w700,
                                                        height: 1.40,
                                                        letterSpacing: 0.18,
                                                      ),
                                                    ),
                                                    TextSpan(
                                                      text: 'Inflow',
                                                      style: TextStyle(
                                                        color: Color(0xFF616161),
                                                        fontSize: 12,
                                                        fontFamily: 'Open Sans',
                                                        fontWeight: FontWeight.w400,
                                                        height: 1.40,
                                                        letterSpacing: 0.18,
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 303,
                child: Container(
                  height: 70.02,
                  padding: const EdgeInsets.symmetric(horizontal: 17.52, vertical: 12),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    border: Border(
                      left: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      top: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      right: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                      bottom: BorderSide(
                        width: 0.75,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99E1E6F0),
                      ),
                    ),
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: double.infinity,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Expanded(
                              child: Container(
                                height: 46.02,
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(7.01),
                                      decoration: ShapeDecoration(
                                        color: Color(0x1478C8E1),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(87.62),
                                        ),
                                      ),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          Container(
                                            padding: const EdgeInsets.all(8),
                                            decoration: ShapeDecoration(
                                              gradient: LinearGradient(
                                                begin: Alignment(-0.96, 0.28),
                                                end: Alignment(0.96, -0.28),
                                                colors: [Color(0xFF022E64), Color(0xFF0E5CBD)],
                                              ),
                                              shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(876.17),
                                              ),
                                            ),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              crossAxisAlignment: CrossAxisAlignment.center,
                                              children: [
                                                Container(
                                                  width: 16,
                                                  height: 16,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 16,
                                                          height: 16,
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 5.33,
                                                                top: 5,
                                                                child: Container(
                                                                  width: 4.67,
                                                                  height: 6,
                                                                  child: Stack(children: [
                                                                  ]),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    const SizedBox(width: 14.02),
                                    Expanded(
                                      child: Container(
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Container(
                                              width: 280.37,
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                                crossAxisAlignment: CrossAxisAlignment.start,
                                                children: [
                                                  Container(
                                                    height: 22.51,
                                                    child: Row(
                                                      mainAxisSize: MainAxisSize.min,
                                                      mainAxisAlignment: MainAxisAlignment.start,
                                                      crossAxisAlignment: CrossAxisAlignment.center,
                                                      children: [
                                                        Text(
                                                          'GHC 50.00',
                                                          style: TextStyle(
                                                            color: Color(0xFF212121),
                                                            fontSize: 16,
                                                            fontFamily: 'Open Sans',
                                                            fontWeight: FontWeight.w700,
                                                            height: 1.20,
                                                          ),
                                                        ),
                                                        const SizedBox(width: 7.01),
                                                        Container(
                                                          padding: const EdgeInsets.symmetric(horizontal: 8.76, vertical: 5.26),
                                                          decoration: ShapeDecoration(
                                                            color: Color(0x1478C8E1),
                                                            shape: RoundedRectangleBorder(
                                                              borderRadius: BorderRadius.circular(5.26),
                                                            ),
                                                          ),
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Text(
                                                                'Debit',
                                                                style: TextStyle(
                                                                  color: Color(0xFF022E64),
                                                                  fontSize: 9,
                                                                  fontFamily: 'Open Sans',
                                                                  fontWeight: FontWeight.w600,
                                                                  letterSpacing: 0.18,
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                  const SizedBox(width: 8),
                                                  Text(
                                                    '01-02-2021',
                                                    style: TextStyle(
                                                      color: Color(0xFF616161),
                                                      fontSize: 10,
                                                      fontFamily: 'Open Sans',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1.40,
                                                      letterSpacing: 0.18,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            const SizedBox(height: 5.26),
                                            SizedBox(
                                              width: double.infinity,
                                              child: Text.rich(
                                                TextSpan(
                                                  children: [
                                                    TextSpan(
                                                      text: '#',
                                                      style: TextStyle(
                                                        color: Color(0xFF022E64),
                                                        fontSize: 12,
                                                        fontFamily: 'Open Sans',
                                                        fontWeight: FontWeight.w700,
                                                        height: 1.40,
                                                        letterSpacing: 0.18,
                                                      ),
                                                    ),
                                                    TextSpan(
                                                      text: 'Gift',
                                                      style: TextStyle(
                                                        color: Color(0xFF616161),
                                                        fontSize: 12,
                                                        fontFamily: 'Open Sans',
                                                        fontWeight: FontWeight.w400,
                                                        height: 1.40,
                                                        letterSpacing: 0.18,
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 103,
                child: Container(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 375,
                              height: 156,
                              padding: const EdgeInsets.symmetric(horizontal: 16),
                              decoration: BoxDecoration(
                                gradient: LinearGradient(
                                  begin: Alignment(0.44, -0.90),
                                  end: Alignment(-0.44, 0.9),
                                  colors: [Color(0xFFE0AD0F), Color(0xFFA07701)],
                                ),
                              ),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Container(
                                    width: double.infinity,
                                    height: 62,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Opacity(
                                          opacity: 0.80,
                                          child: Text(
                                            'Account Balance',
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 14,
                                              fontFamily: 'Open Sans',
                                              fontWeight: FontWeight.w600,
                                              height: 1.20,
                                            ),
                                          ),
                                        ),
                                        const SizedBox(height: 2),
                                        Text(
                                          'GHC 10,000.00',
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 36,
                                            fontFamily: 'Open Sans',
                                            fontWeight: FontWeight.w700,
                                            height: 1.20,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  const SizedBox(height: 8),
                                  Container(
                                    width: double.infinity,
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Opacity(
                                          opacity: 0.80,
                                          child: Text(
                                            'Checking Account',
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 10,
                                              fontFamily: 'Open Sans',
                                              fontWeight: FontWeight.w600,
                                              height: 1.20,
                                              letterSpacing: 1.50,
                                            ),
                                          ),
                                        ),
                                        const SizedBox(width: 8),
                                        Opacity(
                                          opacity: 0.80,
                                          child: Text(
                                            '875431143137098707',
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 10,
                                              fontFamily: 'Open Sans',
                                              fontWeight: FontWeight.w600,
                                              height: 1.20,
                                              letterSpacing: 1.50,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: double.infinity,
                        height: 42,
                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                        decoration: BoxDecoration(color: Color(0x51E1E6F0)),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Expanded(
                              child: Container(
                                height: 17,
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Expanded(
                                      child: Container(
                                        height: 17,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            Text(
                                              'Recent Transactions',
                                              style: TextStyle(
                                                color: Color(0xFF001530),
                                                fontSize: 14,
                                                fontFamily: 'Open Sans',
                                                fontWeight: FontWeight.w600,
                                                height: 1.20,
                                              ),
                                            ),
                                            const SizedBox(width: 8),
                                            Text(
                                              'See All',
                                              style: TextStyle(
                                                color: Color(0xFF022E64),
                                                fontSize: 12,
                                                fontFamily: 'Open Sans',
                                                fontWeight: FontWeight.w400,
                                                letterSpacing: 0.18,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 37.55,
                child: Container(
                  padding: const EdgeInsets.only(
                    top: 8,
                    left: 16,
                    right: 16,
                    bottom: 16,
                  ),
                  decoration: BoxDecoration(
                    color: Color(0xFF022E64),
                    border: Border(
                      left: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99022E64),
                      ),
                      top: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99022E64),
                      ),
                      right: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99022E64),
                      ),
                      bottom: BorderSide(
                        width: 2,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0x99022E64),
                      ),
                    ),
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: 343,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              height: 42,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 52.12,
                                    height: 42,
                                    decoration: BoxDecoration(
                                      image: DecorationImage(
                                        image: NetworkImage("https://via.placeholder.com/52x42"),
                                        fit: BoxFit.fill,
                                      ),
                                    ),
                                  ),
                                  const SizedBox(width: 7),
                                  Container(
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Opacity(
                                          opacity: 0.80,
                                          child: Text(
                                            'Good Morning',
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 12,
                                              fontFamily: 'Open Sans',
                                              fontWeight: FontWeight.w600,
                                              height: 1.20,
                                            ),
                                          ),
                                        ),
                                        const SizedBox(height: 4),
                                        Text(
                                          'Mr. John Jimoh',
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 16,
                                            fontFamily: 'Open Sans',
                                            fontWeight: FontWeight.w600,
                                            height: 1.20,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(width: 8),
                            Container(
                              width: 81.03,
                              height: 32,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/81x32"),
                                  fit: BoxFit.cover,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 740,
                child: Container(
                  width: 375,
                  height: 72,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 375,
                          height: 72,
                          decoration: BoxDecoration(
                            color: Colors.white,
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x0C022E64),
                                blurRadius: 24,
                                offset: Offset(0, -2),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 375,
                          height: 72,
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Expanded(
                                child: Container(
                                  height: double.infinity,
                                  padding: const EdgeInsets.symmetric(vertical: 8),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        padding: const EdgeInsets.all(4),
                                        decoration: ShapeDecoration(
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(14),
                                          ),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            Container(
                                              width: 32,
                                              height: 32,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: 0,
                                                    top: 0,
                                                    child: Container(
                                                      width: 32,
                                                      height: 32,
                                                      child: Stack(children: [
                                                      ]),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      Text(
                                        'Home',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Color(0xFFE6B014),
                                          fontSize: 11,
                                          fontFamily: 'Open Sans',
                                          fontWeight: FontWeight.w700,
                                          height: 1.45,
                                          letterSpacing: 0.50,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Expanded(
                                child: Container(
                                  height: double.infinity,
                                  padding: const EdgeInsets.symmetric(vertical: 8),
                                  decoration: BoxDecoration(
                                    border: Border(
                                      left: BorderSide(width: 0.25),
                                      top: BorderSide(),
                                      right: BorderSide(),
                                      bottom: BorderSide(),
                                    ),
                                  ),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        padding: const EdgeInsets.all(4),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            Container(
                                              width: 32,
                                              height: 32,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: 0,
                                                    top: 0,
                                                    child: Container(
                                                      width: 32,
                                                      height: 32,
                                                      child: Stack(children: [
                                                      ]),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      Text(
                                        'Transactions',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Color(0xFF022E64),
                                          fontSize: 11,
                                          fontFamily: 'Open Sans',
                                          fontWeight: FontWeight.w400,
                                          height: 1.45,
                                          letterSpacing: 0.50,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}